### ISSUE TITLE
Fix this and make it a null check

### ISSUE THREAD

**Issue by hfoxwell** [hfoxwell/Cats-On-Canvas#16]
https://github.com/hfoxwell/Cats-On-Canvas/blob/3aebd641772608daad31d256a969f5902a4f9c6c/src/Clients/user.py#L20

**Comment by vijaybirju** [comment]
Hey hfoxwell , 
I want to work on this issue. can you provide more detail? Instead of checking its length, I have to check whether it is Null or not.
